force-app/main/default/objects/Account/fields/Bairro__c.field-meta.xml
<CustomField>
    <fullName>Bairro__c</fullName>
    <description>Bairro - Endereço</description>
    <label>Bairro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CEP__c.field-meta.xml
<CustomField>
    <fullName>CEP__c</fullName>
    <description>CEP</description>
    <label>CEP</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <description>Cidade - Endereço</description>
    <label>Cidade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Data_de_Nascimento__c.field-meta.xml
<CustomField>
    <fullName>Data_de_Nascimento__c</fullName>
    <label>Data de Nascimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <description>Estado - Endereço</description>
    <label>Estado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Logradouro__c.field-meta.xml
<CustomField>
    <fullName>Logradouro__c</fullName>
    <description>Logradouro - Endereço</description>
    <label>Logradouro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/NumeroApartamento__c.field-meta.xml
<CustomField>
    <fullName>NumeroApartamento__c</fullName>
    <description>Número/Apartamento - Endereço</description>
    <label>Número/Apartamento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Telefone__c.field-meta.xml
<CustomField>
    <fullName>Telefone__c</fullName>
    <label>Telefone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dependente__c/Dependente__c.object-meta.xml
<CustomObject>
    <description>Dependente</description>
    <label>Dependente</label>
    <nameField>
        <label>Dependente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dependentes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dependente__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dependentes</relationshipLabel>
    <relationshipName>Dependentes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dependente__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Ativo</description>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dependente__c/fields/Bairro__c.field-meta.xml
<CustomField>
    <fullName>Bairro__c</fullName>
    <description>Bairro - Endereço</description>
    <label>Bairro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dependente__c/fields/CEP__c.field-meta.xml
<CustomField>
    <fullName>CEP__c</fullName>
    <description>CEP - Endereço</description>
    <label>CEP</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dependente__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <description>Cidade - Endereço</description>
    <label>Cidade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dependente__c/fields/DataNascimento__c.field-meta.xml
<CustomField>
    <fullName>DataNascimento__c</fullName>
    <description>Data de Nascimento</description>
    <label>Data de Nascimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dependente__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Descrição</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Dependente__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <description>Estado - Endereço</description>
    <label>Estado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dependente__c/fields/Logradouro__c.field-meta.xml
<CustomField>
    <fullName>Logradouro__c</fullName>
    <description>Logradouro - Endereço</description>
    <label>Logradouro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dependente__c/fields/NumeroApartamento__c.field-meta.xml
<CustomField>
    <fullName>NumeroApartamento__c</fullName>
    <description>Número/Apartamento - Endereço</description>
    <label>Número/Apartamento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CadastroClienteController.cls
public with sharing class CadastroClienteController {
    // Método para buscar endereço pelo CEP usando o serviço ViaCepService
     @AuraEnabled(cacheable=true)
    public static Map<String, String> buscarCep(String cep) {
        try {
            ViaCepService.Endereco endereco = ViaCepService.buscarEnderecoPorCep(cep);

            Map<String, String> resultado = new Map<String, String>();
            resultado.put('logradouro', endereco.logradouro);
            resultado.put('bairro', endereco.bairro);
            resultado.put('cidade', endereco.cidade);
            resultado.put('estado', endereco.estado);

            return resultado;

        } catch (Exception e) {
            throw new AuraHandledException('Erro ao buscar CEP: ' + e.getMessage());
        }
    }
    // Método para salvar um novo Account (Cliente)
    @AuraEnabled
    public static void salvarAccount(String nome, String email, String telefone, String logradouro, String numero, String cep, String bairro, String cidade, String estado, Date dataNascimento, String descricao) {
        Account acc = new Account();
        acc.Name = nome;
        acc.Email__c = email;
        acc.Telefone__c = telefone;
        acc.Logradouro__c = logradouro; 
        acc.NumeroApartamento__c = numero;
        acc.CEP__c = cep;  
        acc.Bairro__c = bairro; 
        acc.Cidade__c = cidade;
        acc.Estado__c = estado; 
        acc.Data_de_Nascimento__c = dataNascimento;
        acc.Description = descricao;  
        acc.Active__c = 'yes';
        insert acc;
        System.debug('Telefone :' + telefone);
    }
    // Método para salvar um novo Dependente__c relacionado a um Account
    @AuraEnabled
    public static void salvarDependente(String nome, String email, String telefone, String logradouro, String numero, String bairro, String cep, String cidade, String estado,  Date dataNascimento, String descricao, Id accountId) {
        Dependente__c dep = new Dependente__c();
        dep.Name = nome;        
        dep.Email__c = email;
        dep.Telefone__c = telefone;
        dep.Logradouro__c = logradouro;
        dep.NumeroApartamento__c = numero;
        dep.CEP__c = cep;
        dep.Bairro__c = bairro;
        dep.Cidade__c = cidade;
        dep.Estado__c = estado;
        dep.DataNascimento__c = dataNascimento;
        dep.Account__c = accountId;
        dep.Descricao__c = descricao;
        dep.Ativo__c = true;
        insert dep;
        System.debug('Telefone :' + telefone);
    }

 

}